// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srs-info.proto

#ifndef PROTOBUF_INCLUDED_srs_2dinfo_2eproto
#define PROTOBUF_INCLUDED_srs_2dinfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_srs_2dinfo_2eproto 

namespace protobuf_srs_2dinfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_srs_2dinfo_2eproto
namespace protocol {
class CHANNLE_EST;
class CHANNLE_ESTDefaultTypeInternal;
extern CHANNLE_ESTDefaultTypeInternal _CHANNLE_EST_default_instance_;
class NR_SRS_IQ_EST;
class NR_SRS_IQ_ESTDefaultTypeInternal;
extern NR_SRS_IQ_ESTDefaultTypeInternal _NR_SRS_IQ_EST_default_instance_;
}  // namespace protocol
namespace google {
namespace protobuf {
template<> ::protocol::CHANNLE_EST* Arena::CreateMaybeMessage<::protocol::CHANNLE_EST>(Arena*);
template<> ::protocol::NR_SRS_IQ_EST* Arena::CreateMaybeMessage<::protocol::NR_SRS_IQ_EST>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protocol {

// ===================================================================

class NR_SRS_IQ_EST : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.NR_SRS_IQ_EST) */ {
 public:
  NR_SRS_IQ_EST();
  virtual ~NR_SRS_IQ_EST();

  NR_SRS_IQ_EST(const NR_SRS_IQ_EST& from);

  inline NR_SRS_IQ_EST& operator=(const NR_SRS_IQ_EST& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NR_SRS_IQ_EST(NR_SRS_IQ_EST&& from) noexcept
    : NR_SRS_IQ_EST() {
    *this = ::std::move(from);
  }

  inline NR_SRS_IQ_EST& operator=(NR_SRS_IQ_EST&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NR_SRS_IQ_EST& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NR_SRS_IQ_EST* internal_default_instance() {
    return reinterpret_cast<const NR_SRS_IQ_EST*>(
               &_NR_SRS_IQ_EST_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(NR_SRS_IQ_EST* other);
  friend void swap(NR_SRS_IQ_EST& a, NR_SRS_IQ_EST& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NR_SRS_IQ_EST* New() const final {
    return CreateMaybeMessage<NR_SRS_IQ_EST>(NULL);
  }

  NR_SRS_IQ_EST* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NR_SRS_IQ_EST>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NR_SRS_IQ_EST& from);
  void MergeFrom(const NR_SRS_IQ_EST& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NR_SRS_IQ_EST* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .protocol.CHANNLE_EST CHANNLE_EST_LIST = 4;
  int channle_est_list_size() const;
  void clear_channle_est_list();
  static const int kCHANNLEESTLISTFieldNumber = 4;
  ::protocol::CHANNLE_EST* mutable_channle_est_list(int index);
  ::google::protobuf::RepeatedPtrField< ::protocol::CHANNLE_EST >*
      mutable_channle_est_list();
  const ::protocol::CHANNLE_EST& channle_est_list(int index) const;
  ::protocol::CHANNLE_EST* add_channle_est_list();
  const ::google::protobuf::RepeatedPtrField< ::protocol::CHANNLE_EST >&
      channle_est_list() const;

  // @@protoc_insertion_point(class_scope:protocol.NR_SRS_IQ_EST)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::protocol::CHANNLE_EST > channle_est_list_;
  friend struct ::protobuf_srs_2dinfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CHANNLE_EST : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protocol.CHANNLE_EST) */ {
 public:
  CHANNLE_EST();
  virtual ~CHANNLE_EST();

  CHANNLE_EST(const CHANNLE_EST& from);

  inline CHANNLE_EST& operator=(const CHANNLE_EST& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CHANNLE_EST(CHANNLE_EST&& from) noexcept
    : CHANNLE_EST() {
    *this = ::std::move(from);
  }

  inline CHANNLE_EST& operator=(CHANNLE_EST&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CHANNLE_EST& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CHANNLE_EST* internal_default_instance() {
    return reinterpret_cast<const CHANNLE_EST*>(
               &_CHANNLE_EST_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CHANNLE_EST* other);
  friend void swap(CHANNLE_EST& a, CHANNLE_EST& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CHANNLE_EST* New() const final {
    return CreateMaybeMessage<CHANNLE_EST>(NULL);
  }

  CHANNLE_EST* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CHANNLE_EST>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CHANNLE_EST& from);
  void MergeFrom(const CHANNLE_EST& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CHANNLE_EST* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 image = 1;
  bool has_image() const;
  void clear_image();
  static const int kImageFieldNumber = 1;
  ::google::protobuf::int32 image() const;
  void set_image(::google::protobuf::int32 value);

  // required int32 real = 2;
  bool has_real() const;
  void clear_real();
  static const int kRealFieldNumber = 2;
  ::google::protobuf::int32 real() const;
  void set_real(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protocol.CHANNLE_EST)
 private:
  void set_has_image();
  void clear_has_image();
  void set_has_real();
  void clear_has_real();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 image_;
  ::google::protobuf::int32 real_;
  friend struct ::protobuf_srs_2dinfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NR_SRS_IQ_EST

// repeated .protocol.CHANNLE_EST CHANNLE_EST_LIST = 4;
inline int NR_SRS_IQ_EST::channle_est_list_size() const {
  return channle_est_list_.size();
}
inline void NR_SRS_IQ_EST::clear_channle_est_list() {
  channle_est_list_.Clear();
}
inline ::protocol::CHANNLE_EST* NR_SRS_IQ_EST::mutable_channle_est_list(int index) {
  // @@protoc_insertion_point(field_mutable:protocol.NR_SRS_IQ_EST.CHANNLE_EST_LIST)
  return channle_est_list_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::protocol::CHANNLE_EST >*
NR_SRS_IQ_EST::mutable_channle_est_list() {
  // @@protoc_insertion_point(field_mutable_list:protocol.NR_SRS_IQ_EST.CHANNLE_EST_LIST)
  return &channle_est_list_;
}
inline const ::protocol::CHANNLE_EST& NR_SRS_IQ_EST::channle_est_list(int index) const {
  // @@protoc_insertion_point(field_get:protocol.NR_SRS_IQ_EST.CHANNLE_EST_LIST)
  return channle_est_list_.Get(index);
}
inline ::protocol::CHANNLE_EST* NR_SRS_IQ_EST::add_channle_est_list() {
  // @@protoc_insertion_point(field_add:protocol.NR_SRS_IQ_EST.CHANNLE_EST_LIST)
  return channle_est_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protocol::CHANNLE_EST >&
NR_SRS_IQ_EST::channle_est_list() const {
  // @@protoc_insertion_point(field_list:protocol.NR_SRS_IQ_EST.CHANNLE_EST_LIST)
  return channle_est_list_;
}

// -------------------------------------------------------------------

// CHANNLE_EST

// required int32 image = 1;
inline bool CHANNLE_EST::has_image() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CHANNLE_EST::set_has_image() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CHANNLE_EST::clear_has_image() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CHANNLE_EST::clear_image() {
  image_ = 0;
  clear_has_image();
}
inline ::google::protobuf::int32 CHANNLE_EST::image() const {
  // @@protoc_insertion_point(field_get:protocol.CHANNLE_EST.image)
  return image_;
}
inline void CHANNLE_EST::set_image(::google::protobuf::int32 value) {
  set_has_image();
  image_ = value;
  // @@protoc_insertion_point(field_set:protocol.CHANNLE_EST.image)
}

// required int32 real = 2;
inline bool CHANNLE_EST::has_real() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CHANNLE_EST::set_has_real() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CHANNLE_EST::clear_has_real() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CHANNLE_EST::clear_real() {
  real_ = 0;
  clear_has_real();
}
inline ::google::protobuf::int32 CHANNLE_EST::real() const {
  // @@protoc_insertion_point(field_get:protocol.CHANNLE_EST.real)
  return real_;
}
inline void CHANNLE_EST::set_real(::google::protobuf::int32 value) {
  set_has_real();
  real_ = value;
  // @@protoc_insertion_point(field_set:protocol.CHANNLE_EST.real)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_srs_2dinfo_2eproto
