/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: srs-info.proto */

#ifndef PROTOBUF_C_srs_2dinfo_2eproto__INCLUDED
#define PROTOBUF_C_srs_2dinfo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Protocol__NRSRSIQEST Protocol__NRSRSIQEST;
typedef struct _Protocol__CHANNLEEST Protocol__CHANNLEEST;


/* --- enums --- */


/* --- messages --- */

struct  _Protocol__NRSRSIQEST
{
  ProtobufCMessage base;
  size_t n_channle_est_list;
  Protocol__CHANNLEEST **channle_est_list;
};
#define PROTOCOL__NR__SRS__IQ__EST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__nr__srs__iq__est__descriptor) \
    , 0,NULL }


struct  _Protocol__CHANNLEEST
{
  ProtobufCMessage base;
  int32_t image;
  int32_t real;
};
#define PROTOCOL__CHANNLE__EST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__channle__est__descriptor) \
    , 0, 0 }


/* Protocol__NRSRSIQEST methods */
void   protocol__nr__srs__iq__est__init
                     (Protocol__NRSRSIQEST         *message);
size_t protocol__nr__srs__iq__est__get_packed_size
                     (const Protocol__NRSRSIQEST   *message);
size_t protocol__nr__srs__iq__est__pack
                     (const Protocol__NRSRSIQEST   *message,
                      uint8_t             *out);
size_t protocol__nr__srs__iq__est__pack_to_buffer
                     (const Protocol__NRSRSIQEST   *message,
                      ProtobufCBuffer     *buffer);
Protocol__NRSRSIQEST *
       protocol__nr__srs__iq__est__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__nr__srs__iq__est__free_unpacked
                     (Protocol__NRSRSIQEST *message,
                      ProtobufCAllocator *allocator);
/* Protocol__CHANNLEEST methods */
void   protocol__channle__est__init
                     (Protocol__CHANNLEEST         *message);
size_t protocol__channle__est__get_packed_size
                     (const Protocol__CHANNLEEST   *message);
size_t protocol__channle__est__pack
                     (const Protocol__CHANNLEEST   *message,
                      uint8_t             *out);
size_t protocol__channle__est__pack_to_buffer
                     (const Protocol__CHANNLEEST   *message,
                      ProtobufCBuffer     *buffer);
Protocol__CHANNLEEST *
       protocol__channle__est__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__channle__est__free_unpacked
                     (Protocol__CHANNLEEST *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__NRSRSIQEST_Closure)
                 (const Protocol__NRSRSIQEST *message,
                  void *closure_data);
typedef void (*Protocol__CHANNLEEST_Closure)
                 (const Protocol__CHANNLEEST *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protocol__nr__srs__iq__est__descriptor;
extern const ProtobufCMessageDescriptor protocol__channle__est__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_srs_2dinfo_2eproto__INCLUDED */
