# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srs-info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='srs-info.proto',
  package='protocol',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0esrs-info.proto\x12\x08protocol\"@\n\rNR_SRS_IQ_EST\x12/\n\x10\x43HANNLE_EST_LIST\x18\x04 \x03(\x0b\x32\x15.protocol.CHANNLE_EST\"*\n\x0b\x43HANNLE_EST\x12\r\n\x05image\x18\x01 \x02(\x05\x12\x0c\n\x04real\x18\x02 \x02(\x05')
)




_NR_SRS_IQ_EST = _descriptor.Descriptor(
  name='NR_SRS_IQ_EST',
  full_name='protocol.NR_SRS_IQ_EST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CHANNLE_EST_LIST', full_name='protocol.NR_SRS_IQ_EST.CHANNLE_EST_LIST', index=0,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=92,
)


_CHANNLE_EST = _descriptor.Descriptor(
  name='CHANNLE_EST',
  full_name='protocol.CHANNLE_EST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='protocol.CHANNLE_EST.image', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='real', full_name='protocol.CHANNLE_EST.real', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=136,
)

_NR_SRS_IQ_EST.fields_by_name['CHANNLE_EST_LIST'].message_type = _CHANNLE_EST
DESCRIPTOR.message_types_by_name['NR_SRS_IQ_EST'] = _NR_SRS_IQ_EST
DESCRIPTOR.message_types_by_name['CHANNLE_EST'] = _CHANNLE_EST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NR_SRS_IQ_EST = _reflection.GeneratedProtocolMessageType('NR_SRS_IQ_EST', (_message.Message,), dict(
  DESCRIPTOR = _NR_SRS_IQ_EST,
  __module__ = 'srs_info_pb2'
  # @@protoc_insertion_point(class_scope:protocol.NR_SRS_IQ_EST)
  ))
_sym_db.RegisterMessage(NR_SRS_IQ_EST)

CHANNLE_EST = _reflection.GeneratedProtocolMessageType('CHANNLE_EST', (_message.Message,), dict(
  DESCRIPTOR = _CHANNLE_EST,
  __module__ = 'srs_info_pb2'
  # @@protoc_insertion_point(class_scope:protocol.CHANNLE_EST)
  ))
_sym_db.RegisterMessage(CHANNLE_EST)


# @@protoc_insertion_point(module_scope)
