/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ul_est.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ul_est.pb-c.h"
void   nrpose__nr__srs__info__init
                     (NRpose__NRSRSINFO         *message)
{
  static const NRpose__NRSRSINFO init_value = NRPOSE__NR__SRS__INFO__INIT;
  *message = init_value;
}
size_t nrpose__nr__srs__info__get_packed_size
                     (const NRpose__NRSRSINFO *message)
{
  assert(message->base.descriptor == &nrpose__nr__srs__info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nrpose__nr__srs__info__pack
                     (const NRpose__NRSRSINFO *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nrpose__nr__srs__info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nrpose__nr__srs__info__pack_to_buffer
                     (const NRpose__NRSRSINFO *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nrpose__nr__srs__info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NRpose__NRSRSINFO *
       nrpose__nr__srs__info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NRpose__NRSRSINFO *)
     protobuf_c_message_unpack (&nrpose__nr__srs__info__descriptor,
                                allocator, len, data);
}
void   nrpose__nr__srs__info__free_unpacked
                     (NRpose__NRSRSINFO *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nrpose__nr__srs__info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nrpose__result__init
                     (NRpose__RESULT         *message)
{
  static const NRpose__RESULT init_value = NRPOSE__RESULT__INIT;
  *message = init_value;
}
size_t nrpose__result__get_packed_size
                     (const NRpose__RESULT *message)
{
  assert(message->base.descriptor == &nrpose__result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nrpose__result__pack
                     (const NRpose__RESULT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nrpose__result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nrpose__result__pack_to_buffer
                     (const NRpose__RESULT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nrpose__result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NRpose__RESULT *
       nrpose__result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NRpose__RESULT *)
     protobuf_c_message_unpack (&nrpose__result__descriptor,
                                allocator, len, data);
}
void   nrpose__result__free_unpacked
                     (NRpose__RESULT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nrpose__result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nrpose__nr__srs__info__field_descriptors[5] =
{
  {
    "GEN_SRS",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NRpose__NRSRSINFO, n_gen_srs),
    offsetof(NRpose__NRSRSINFO, gen_srs),
    &nrpose__result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "REC_SRS",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NRpose__NRSRSINFO, n_rec_srs),
    offsetof(NRpose__NRSRSINFO, rec_srs),
    &nrpose__result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LS_SRS",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NRpose__NRSRSINFO, n_ls_srs),
    offsetof(NRpose__NRSRSINFO, ls_srs),
    &nrpose__result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SIGNAL_POWER",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NRpose__NRSRSINFO, signal_power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "NOISE_POWER",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NRpose__NRSRSINFO, noise_power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nrpose__nr__srs__info__field_indices_by_name[] = {
  0,   /* field[0] = GEN_SRS */
  2,   /* field[2] = LS_SRS */
  4,   /* field[4] = NOISE_POWER */
  1,   /* field[1] = REC_SRS */
  3,   /* field[3] = SIGNAL_POWER */
};
static const ProtobufCIntRange nrpose__nr__srs__info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nrpose__nr__srs__info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NRpose.NR_SRS_INFO",
  "NRSRSINFO",
  "NRpose__NRSRSINFO",
  "NRpose",
  sizeof(NRpose__NRSRSINFO),
  5,
  nrpose__nr__srs__info__field_descriptors,
  nrpose__nr__srs__info__field_indices_by_name,
  1,  nrpose__nr__srs__info__number_ranges,
  (ProtobufCMessageInit) nrpose__nr__srs__info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nrpose__result__field_descriptors[2] =
{
  {
    "image",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NRpose__RESULT, image),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "real",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NRpose__RESULT, real),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nrpose__result__field_indices_by_name[] = {
  0,   /* field[0] = image */
  1,   /* field[1] = real */
};
static const ProtobufCIntRange nrpose__result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nrpose__result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NRpose.RESULT",
  "RESULT",
  "NRpose__RESULT",
  "NRpose",
  sizeof(NRpose__RESULT),
  2,
  nrpose__result__field_descriptors,
  nrpose__result__field_indices_by_name,
  1,  nrpose__result__number_ranges,
  (ProtobufCMessageInit) nrpose__result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
