// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ul_srs_est.proto

#ifndef PROTOBUF_ul_5fsrs_5fest_2eproto__INCLUDED
#define PROTOBUF_ul_5fsrs_5fest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace NRpose {
class NR_SRS_INFO;
class NR_SRS_INFODefaultTypeInternal;
extern NR_SRS_INFODefaultTypeInternal _NR_SRS_INFO_default_instance_;
class NR_SRS_PACK;
class NR_SRS_PACKDefaultTypeInternal;
extern NR_SRS_PACKDefaultTypeInternal _NR_SRS_PACK_default_instance_;
class RESULT;
class RESULTDefaultTypeInternal;
extern RESULTDefaultTypeInternal _RESULT_default_instance_;
}  // namespace NRpose

namespace NRpose {

namespace protobuf_ul_5fsrs_5fest_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_ul_5fsrs_5fest_2eproto

// ===================================================================

class NR_SRS_PACK : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NRpose.NR_SRS_PACK) */ {
 public:
  NR_SRS_PACK();
  virtual ~NR_SRS_PACK();

  NR_SRS_PACK(const NR_SRS_PACK& from);

  inline NR_SRS_PACK& operator=(const NR_SRS_PACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NR_SRS_PACK& default_instance();

  static inline const NR_SRS_PACK* internal_default_instance() {
    return reinterpret_cast<const NR_SRS_PACK*>(
               &_NR_SRS_PACK_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(NR_SRS_PACK* other);

  // implements Message ----------------------------------------------

  inline NR_SRS_PACK* New() const PROTOBUF_FINAL { return New(NULL); }

  NR_SRS_PACK* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NR_SRS_PACK& from);
  void MergeFrom(const NR_SRS_PACK& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NR_SRS_PACK* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .NRpose.NR_SRS_INFO ESTIMATION = 1;
  int estimation_size() const;
  void clear_estimation();
  static const int kESTIMATIONFieldNumber = 1;
  const ::NRpose::NR_SRS_INFO& estimation(int index) const;
  ::NRpose::NR_SRS_INFO* mutable_estimation(int index);
  ::NRpose::NR_SRS_INFO* add_estimation();
  ::google::protobuf::RepeatedPtrField< ::NRpose::NR_SRS_INFO >*
      mutable_estimation();
  const ::google::protobuf::RepeatedPtrField< ::NRpose::NR_SRS_INFO >&
      estimation() const;

  // required int32 SIGNAL_POWER = 2;
  bool has_signal_power() const;
  void clear_signal_power();
  static const int kSIGNALPOWERFieldNumber = 2;
  ::google::protobuf::int32 signal_power() const;
  void set_signal_power(::google::protobuf::int32 value);

  // required int32 NOISE_POWER = 3;
  bool has_noise_power() const;
  void clear_noise_power();
  static const int kNOISEPOWERFieldNumber = 3;
  ::google::protobuf::int32 noise_power() const;
  void set_noise_power(::google::protobuf::int32 value);

  // required int32 CALL_TIME = 5;
  bool has_call_time() const;
  void clear_call_time();
  static const int kCALLTIMEFieldNumber = 5;
  ::google::protobuf::int32 call_time() const;
  void set_call_time(::google::protobuf::int32 value);

  // required int32 FUNC_CNT = 6;
  bool has_func_cnt() const;
  void clear_func_cnt();
  static const int kFUNCCNTFieldNumber = 6;
  ::google::protobuf::int32 func_cnt() const;
  void set_func_cnt(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NRpose.NR_SRS_PACK)
 private:
  void set_has_signal_power();
  void clear_has_signal_power();
  void set_has_noise_power();
  void clear_has_noise_power();
  void set_has_call_time();
  void clear_has_call_time();
  void set_has_func_cnt();
  void clear_has_func_cnt();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::NRpose::NR_SRS_INFO > estimation_;
  ::google::protobuf::int32 signal_power_;
  ::google::protobuf::int32 noise_power_;
  ::google::protobuf::int32 call_time_;
  ::google::protobuf::int32 func_cnt_;
  friend struct protobuf_ul_5fsrs_5fest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class NR_SRS_INFO : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NRpose.NR_SRS_INFO) */ {
 public:
  NR_SRS_INFO();
  virtual ~NR_SRS_INFO();

  NR_SRS_INFO(const NR_SRS_INFO& from);

  inline NR_SRS_INFO& operator=(const NR_SRS_INFO& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NR_SRS_INFO& default_instance();

  static inline const NR_SRS_INFO* internal_default_instance() {
    return reinterpret_cast<const NR_SRS_INFO*>(
               &_NR_SRS_INFO_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(NR_SRS_INFO* other);

  // implements Message ----------------------------------------------

  inline NR_SRS_INFO* New() const PROTOBUF_FINAL { return New(NULL); }

  NR_SRS_INFO* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NR_SRS_INFO& from);
  void MergeFrom(const NR_SRS_INFO& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NR_SRS_INFO* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .NRpose.RESULT LS_SRS = 3;
  int ls_srs_size() const;
  void clear_ls_srs();
  static const int kLSSRSFieldNumber = 3;
  const ::NRpose::RESULT& ls_srs(int index) const;
  ::NRpose::RESULT* mutable_ls_srs(int index);
  ::NRpose::RESULT* add_ls_srs();
  ::google::protobuf::RepeatedPtrField< ::NRpose::RESULT >*
      mutable_ls_srs();
  const ::google::protobuf::RepeatedPtrField< ::NRpose::RESULT >&
      ls_srs() const;

  // @@protoc_insertion_point(class_scope:NRpose.NR_SRS_INFO)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::NRpose::RESULT > ls_srs_;
  friend struct protobuf_ul_5fsrs_5fest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RESULT : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NRpose.RESULT) */ {
 public:
  RESULT();
  virtual ~RESULT();

  RESULT(const RESULT& from);

  inline RESULT& operator=(const RESULT& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RESULT& default_instance();

  static inline const RESULT* internal_default_instance() {
    return reinterpret_cast<const RESULT*>(
               &_RESULT_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(RESULT* other);

  // implements Message ----------------------------------------------

  inline RESULT* New() const PROTOBUF_FINAL { return New(NULL); }

  RESULT* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RESULT& from);
  void MergeFrom(const RESULT& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RESULT* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 image = 1;
  bool has_image() const;
  void clear_image();
  static const int kImageFieldNumber = 1;
  ::google::protobuf::int32 image() const;
  void set_image(::google::protobuf::int32 value);

  // required int32 real = 2;
  bool has_real() const;
  void clear_real();
  static const int kRealFieldNumber = 2;
  ::google::protobuf::int32 real() const;
  void set_real(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NRpose.RESULT)
 private:
  void set_has_image();
  void clear_has_image();
  void set_has_real();
  void clear_has_real();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 image_;
  ::google::protobuf::int32 real_;
  friend struct protobuf_ul_5fsrs_5fest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// NR_SRS_PACK

// repeated .NRpose.NR_SRS_INFO ESTIMATION = 1;
inline int NR_SRS_PACK::estimation_size() const {
  return estimation_.size();
}
inline void NR_SRS_PACK::clear_estimation() {
  estimation_.Clear();
}
inline const ::NRpose::NR_SRS_INFO& NR_SRS_PACK::estimation(int index) const {
  // @@protoc_insertion_point(field_get:NRpose.NR_SRS_PACK.ESTIMATION)
  return estimation_.Get(index);
}
inline ::NRpose::NR_SRS_INFO* NR_SRS_PACK::mutable_estimation(int index) {
  // @@protoc_insertion_point(field_mutable:NRpose.NR_SRS_PACK.ESTIMATION)
  return estimation_.Mutable(index);
}
inline ::NRpose::NR_SRS_INFO* NR_SRS_PACK::add_estimation() {
  // @@protoc_insertion_point(field_add:NRpose.NR_SRS_PACK.ESTIMATION)
  return estimation_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::NRpose::NR_SRS_INFO >*
NR_SRS_PACK::mutable_estimation() {
  // @@protoc_insertion_point(field_mutable_list:NRpose.NR_SRS_PACK.ESTIMATION)
  return &estimation_;
}
inline const ::google::protobuf::RepeatedPtrField< ::NRpose::NR_SRS_INFO >&
NR_SRS_PACK::estimation() const {
  // @@protoc_insertion_point(field_list:NRpose.NR_SRS_PACK.ESTIMATION)
  return estimation_;
}

// required int32 SIGNAL_POWER = 2;
inline bool NR_SRS_PACK::has_signal_power() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NR_SRS_PACK::set_has_signal_power() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NR_SRS_PACK::clear_has_signal_power() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NR_SRS_PACK::clear_signal_power() {
  signal_power_ = 0;
  clear_has_signal_power();
}
inline ::google::protobuf::int32 NR_SRS_PACK::signal_power() const {
  // @@protoc_insertion_point(field_get:NRpose.NR_SRS_PACK.SIGNAL_POWER)
  return signal_power_;
}
inline void NR_SRS_PACK::set_signal_power(::google::protobuf::int32 value) {
  set_has_signal_power();
  signal_power_ = value;
  // @@protoc_insertion_point(field_set:NRpose.NR_SRS_PACK.SIGNAL_POWER)
}

// required int32 NOISE_POWER = 3;
inline bool NR_SRS_PACK::has_noise_power() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NR_SRS_PACK::set_has_noise_power() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NR_SRS_PACK::clear_has_noise_power() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NR_SRS_PACK::clear_noise_power() {
  noise_power_ = 0;
  clear_has_noise_power();
}
inline ::google::protobuf::int32 NR_SRS_PACK::noise_power() const {
  // @@protoc_insertion_point(field_get:NRpose.NR_SRS_PACK.NOISE_POWER)
  return noise_power_;
}
inline void NR_SRS_PACK::set_noise_power(::google::protobuf::int32 value) {
  set_has_noise_power();
  noise_power_ = value;
  // @@protoc_insertion_point(field_set:NRpose.NR_SRS_PACK.NOISE_POWER)
}

// required int32 CALL_TIME = 5;
inline bool NR_SRS_PACK::has_call_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NR_SRS_PACK::set_has_call_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NR_SRS_PACK::clear_has_call_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NR_SRS_PACK::clear_call_time() {
  call_time_ = 0;
  clear_has_call_time();
}
inline ::google::protobuf::int32 NR_SRS_PACK::call_time() const {
  // @@protoc_insertion_point(field_get:NRpose.NR_SRS_PACK.CALL_TIME)
  return call_time_;
}
inline void NR_SRS_PACK::set_call_time(::google::protobuf::int32 value) {
  set_has_call_time();
  call_time_ = value;
  // @@protoc_insertion_point(field_set:NRpose.NR_SRS_PACK.CALL_TIME)
}

// required int32 FUNC_CNT = 6;
inline bool NR_SRS_PACK::has_func_cnt() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NR_SRS_PACK::set_has_func_cnt() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NR_SRS_PACK::clear_has_func_cnt() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NR_SRS_PACK::clear_func_cnt() {
  func_cnt_ = 0;
  clear_has_func_cnt();
}
inline ::google::protobuf::int32 NR_SRS_PACK::func_cnt() const {
  // @@protoc_insertion_point(field_get:NRpose.NR_SRS_PACK.FUNC_CNT)
  return func_cnt_;
}
inline void NR_SRS_PACK::set_func_cnt(::google::protobuf::int32 value) {
  set_has_func_cnt();
  func_cnt_ = value;
  // @@protoc_insertion_point(field_set:NRpose.NR_SRS_PACK.FUNC_CNT)
}

// -------------------------------------------------------------------

// NR_SRS_INFO

// repeated .NRpose.RESULT LS_SRS = 3;
inline int NR_SRS_INFO::ls_srs_size() const {
  return ls_srs_.size();
}
inline void NR_SRS_INFO::clear_ls_srs() {
  ls_srs_.Clear();
}
inline const ::NRpose::RESULT& NR_SRS_INFO::ls_srs(int index) const {
  // @@protoc_insertion_point(field_get:NRpose.NR_SRS_INFO.LS_SRS)
  return ls_srs_.Get(index);
}
inline ::NRpose::RESULT* NR_SRS_INFO::mutable_ls_srs(int index) {
  // @@protoc_insertion_point(field_mutable:NRpose.NR_SRS_INFO.LS_SRS)
  return ls_srs_.Mutable(index);
}
inline ::NRpose::RESULT* NR_SRS_INFO::add_ls_srs() {
  // @@protoc_insertion_point(field_add:NRpose.NR_SRS_INFO.LS_SRS)
  return ls_srs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::NRpose::RESULT >*
NR_SRS_INFO::mutable_ls_srs() {
  // @@protoc_insertion_point(field_mutable_list:NRpose.NR_SRS_INFO.LS_SRS)
  return &ls_srs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::NRpose::RESULT >&
NR_SRS_INFO::ls_srs() const {
  // @@protoc_insertion_point(field_list:NRpose.NR_SRS_INFO.LS_SRS)
  return ls_srs_;
}

// -------------------------------------------------------------------

// RESULT

// required int32 image = 1;
inline bool RESULT::has_image() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RESULT::set_has_image() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RESULT::clear_has_image() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RESULT::clear_image() {
  image_ = 0;
  clear_has_image();
}
inline ::google::protobuf::int32 RESULT::image() const {
  // @@protoc_insertion_point(field_get:NRpose.RESULT.image)
  return image_;
}
inline void RESULT::set_image(::google::protobuf::int32 value) {
  set_has_image();
  image_ = value;
  // @@protoc_insertion_point(field_set:NRpose.RESULT.image)
}

// required int32 real = 2;
inline bool RESULT::has_real() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RESULT::set_has_real() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RESULT::clear_has_real() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RESULT::clear_real() {
  real_ = 0;
  clear_has_real();
}
inline ::google::protobuf::int32 RESULT::real() const {
  // @@protoc_insertion_point(field_get:NRpose.RESULT.real)
  return real_;
}
inline void RESULT::set_real(::google::protobuf::int32 value) {
  set_has_real();
  real_ = value;
  // @@protoc_insertion_point(field_set:NRpose.RESULT.real)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace NRpose

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ul_5fsrs_5fest_2eproto__INCLUDED
